owner: authdog-monitoring # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Authdog Website
    url: https://www.authdog.com

  - name: Authdog Platform API
    url: https://api.authdog.com/api/v1/health

status-website:
  baseUrl: /$REPO
  logoUrl: https://res.cloudinary.com/authdog/image/upload/v1632157556/Web/images/corporate/Authdog_Full-Colour_lf2qex.svg
  name: Status App
  navbar:
    - title: Home
      href: /$REPO
    - title: Website
      href: https://www.authdog.com

