owner: authdog-monitoring
repo: status

sites:
  - name: Website
    url: https://www.authdog.com
  - name: Platform API (us-east-1)
    url: https://api.authdog.com/api/v1/health
  - name: Cloudflare Worker Test
    url: https://my-ts-project.authdog.workers.dev
  - name: Vercel Sandbox
    url: https://api-rest-vercel-dbrrt.vercel.app
  - name: Vercel SLS Wrapper
    url: https://atdg-test-deploy.vercel.app/api/v1/health
  - name: Fastly JS Compute
    url: https://quick-gloating-palpable.edgecompute.app/hello
    
status-website:
  logoUrl: https://res.cloudinary.com/authdog/image/upload/v1632157556/Web/images/corporate/Authdog_Full-Colour_lf2qex.svg
  cname: alt.status.authdog.com
  name: Status
  navbar:
    - title: Home
      href: /
    - title: Website
      href: https://www.authdog.com
    - title: Open Source
      href: https://www.github.com/authdog

assignees:
  - dbrrt
  
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
